"""seed_mongo.py
Utility script to read the generated ``random_profiles.json`` file and insert the
profiles into the MongoDB Atlas collection used by the backend.

Run it after you have started the virtual environment and ensured that the
environment variable ``MONGODB_URL`` is set (Render injects it automatically; for
local testing you can export it manually).

Usage:
    python demo/seed_mongo.py
"""

import os
import json
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient

# Load .env file if present
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Path to the JSON file generated by ``create_random_profiles.py``
JSON_PATH = os.path.join(os.path.dirname(__file__), "random_profiles.json")

async def main():
    # Load profiles from JSON
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        profiles = json.load(f)
    print(f"✅ Loaded {len(profiles)} profiles from {JSON_PATH}")

    # Get MongoDB connection string from environment
    mongo_url = os.getenv("MONGODB_URL")
    if not mongo_url:
        raise RuntimeError("MONGODB_URL environment variable not set. Set it before running this script.")

    client = AsyncIOMotorClient(mongo_url)
    db = client.get_default_database()  # uses DB name from the URI
    collection = db["profiles"]

    # Optional: clear existing collection first
    await collection.delete_many({})
    print("🗑️  Cleared existing documents in the 'profiles' collection")

    # Insert all profiles (MongoDB will generate _id for each)
    result = await collection.insert_many(profiles)
    print(f"🚀 Inserted {len(result.inserted_ids)} profiles into MongoDB")

    # Close the client
    client.close()

if __name__ == "__main__":
    asyncio.run(main())
